version: 2
jobs:
  publish-test:
      docker:
        - image: python:3.6
      steps:
        - run: pip install --user twine
        - checkout
        - run: python setup.py sdist bdist_wheel --universal
        - run: ~/.local/bin/twine upload -u flambe -p $PYPI_TEST_PASS --repository-url https://test.pypi.org/legacy/ dist/*
 

workflows:
  version: 2
  build:
    jobs:
      - echo
