version: 2
jobs:
  test:
      docker:
        - image: python:3.6
      steps:
        - checkout
        - run: python3 -m pip install --user tox awscli
        - run: python3 -m awscli configure set region us-east-1
        - run:
            command: python3 -m tox -- -m "not end2end" -v
            no_output_timeout: 30m

  publish-test:
      docker:
        - image: python:3.6
      steps:
        - run: pip install --user twine
        - checkout
        - run: python setup.py sdist bdist_wheel --universal
        - run: ~/.local/bin/twine upload -u flambe -p $PYPI_TEST_PASS --repository-url https://test.pypi.org/legacy/ dist/*
  publish:
      docker:
        - image: python:3.6
      steps:
        - run: pip install --user twine
        - checkout
        - run: python setup.py sdist bdist_wheel --universal
        - run: ~/.local/bin/twine upload -u flambe -p $PYPI_PASS dist/*

workflows:
  version: 2
  build:
    jobs:
      - test
      - publish-test:
          requires:
            - test
          filters:
            tags:
              only:
                - /^[0-9]+(\.[0-9]+)*/
            branches:
              ignore:
                - /.*/
      - publish:
          requires:
            - publish-test
          filters:
            tags:
              only:
                - /^[0-9]+(\.[0-9]+)*/
            branches:
              ignore:
                - /.*/
